name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies UA-CloudLibrary
      run: dotnet restore UACloudLibraryServer\UA-CloudLibrary.csproj
    - name: Restore dependencies UACloudLibClientLibrary
      run: dotnet restore UACloudLibraryGraphQLClient\UACloudLibClientLibrary\Opc.Ua.CloudLib.Client.csproj
    - name: Restore dependencies SampleConsoleClient
      run: dotnet restore SampleConsoleClient\SampleConsoleClient.csproj
    - name: Build
      run: dotnet build UA-CloudLibrary.sln --configuration Release --no-restore
    - name: pack NuGet
      run: dotnet pack UACloudLibraryGraphQLClient\UACloudLibClientLibrary\Opc.Ua.CloudLib.Client.csproj --configuration Release
    - name: publish NuGet
      run: dotnet nuget push "bin\Release\*.nupkg"  --api-key YOUR_GITHUB_PAT --source "github"
    - name: Test
      run: dotnet test UA-CloudLibrary.sln --no-build --verbosity normal
